fastlane_version '2.157'
default_platform :ios
xcversion(version: "13.4.1") # Selects Xcode 8.1.0
# Variable
DERIVED_DATA_PATH = "#{ENV['CIRCLE_DERIVED_DATA_PATH']}"
TESTS_REPORTS_PATH = "#{ENV['CIRCLE_TESTS_REPORTS_PATH']}"
LOG_PATH = "#{ENV['CIRCLE_LOG_PATH']}"
WORKSPACE = "#{ENV['ZALOPAY_APP_XCODE_WORKSPACE']}"
PROJECT = "#{ENV['ZALOPAY_APP_XCODE_PROJECT']}"
SERVICE_CREDENTIALS_FILE = "#{ENV['SERVICE_CREDENTIALS_FILE_PATH']}"

platform :ios do
    lane :install_pods do
      cocoapods(
          clean: true,
          use_bundle_exec: false
    )
    end

    lane :tests do
      scan(
        workspace: 'ExamCountdown.xcworkspace',
        scheme: 'ExamCountdown',
        clean: true,
        code_coverage: true,
        output_types: "junit",
        output_directory: TESTS_REPORTS_PATH,
        derived_data_path: DERIVED_DATA_PATH,
        buildlog_path: LOG_PATH
      )
    end

    lane :build_ipa do
      build_ios_app(
        workspace: "ExamCountdown.xcworkspace",
        configuration: "Debug",
        scheme: "ExamCountdown",
        silent: true,
        clean: true,
        export_method: "development",
        output_name: "countdown.ipa"       # specify the name of the .ipa file to generate (including file extension)
      )
    end

    lane :submit_firebase do
      firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        firebase_cli_token: "1//0e-jAs3cu-UxACgYIARAAGA4SNwF-L9IrWZF9vQgLnKbygVYDcbrpU13iu8egJRLXqEEQTFXV5gPN_UoxSwyjvQmQBEkiwtExh_s",
        release_notes_file: ENV['RELEASE_NOTES_FILE'],
        # service_credentials_file: "Fastlane/examcountdown.json",
        ipa_path: "Build/countdown.ipa",
        debug: true
      )
    end
end