name: Pull Request

on:
  pull_request:
    branches:
      - 'main'
      - 'features/**'
      - 'release/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: bundle exec fastlane tests

      - name: Run Tests (No Cache)
        if: steps.setup.outputs.cache-hit != 'true'
        run: bundle exec fastlane tests
      
      - name: Run Tests (Cache)
        if: steps.setup.outputs.cache-hit == 'true'
        run: bundle exec fastlane tests skip_package_dependencies_resolution:true
  
  log:
    needs: test
    runs-on: macos-11
    steps:
      - run: echo "Hello world"
