name: Pull Request

on:
  push:
    branches:
      - 'main'
      - 'develop'
      - 'features/**'
      - 'release/**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: macos-12
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

  test:
    needs: setup
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          if [[ -z "${{ steps.setup.outputs.cache-hit }}" ]]; then
            bundle exec fastlane tests
          else
            bundle exec fastlane tests skip_package_dependencies_resolution:true
          fi

  log:
    needs: test
    runs-on: macos-11
    steps:
      - run: echo "Hello world"
