name: PULL REQUEST

on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'features/**'
      - 'release/**'
  workflow_dispatch:

jobs:
  setup:
    runs-on: macos-12
    if: github.event_name == 'pull_request' && github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Bundler
        run: gem install bundler

      - name: Install gems
        run: bundle install

      - name: Swift Packages Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('BILDsolid.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

  distribute:
    needs: setup
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install Fastlane
        run: gem install fastlane

      - name: Build ipa
        run: bundle exec fastlane build_ipa

      - name: Build ipa
        run: bundle exec fastlane increment_version

      - name: submit firebase
        run: bundle exec fastlane submit_firebase
